### PR TITLE
Updated Php, added responding via closure, tests for zeroOrMoreTimes

### PR DESCRIPTION
**Pull request by maartenderie**
Please see the commit messages.
Let me know what you think and what can be changed. Hopefully it's not too much changes in one PR.

### CODE REVIEW

**Comment by maartenderie** [comment]
Could someone give me some feedback please?

**Comment by LarsLuz** [comment]
Hello,

I'm terribly sorry that I am a year late to respond to your pull request.

We did test your branch, everything seems to be running fine.
I've reviewed the code and everything looks good for me

Thank you for your patience, my colleague will accept the pull request

**Comment by maartenderie** [comment]
> Hello,
> 
> I'm terribly sorry that I am a year late to respond to your pull request.
> 
> We did test your branch, everything seems to be running fine.
> I've reviewed the code and everything looks good for me
> 
> Thank you for your patience, my colleague will accept the pull request

I forgot about this one! Thanks for getting back. I might propose some more changes, since I'm still using this library.

Have a great day!

**Comment by LarsLuz** [comment]
Thanks! We've just updated it for PHP 8 compatibility
Feel free to propose changes

**Pull request merged**
